### ISSUE TITLE
[Bug 🐞]: ED logging Exception, which is explicitly stated as not being an error.

### ISSUE THREAD

**Issue by Alpaccalypse** [zer0Kerbal/ExceptionDetector#40] opened 2023-05-02 06:00 UTC
### Brief description of your issue (aka the problem)

Relevant code snippet:

`[LOG 06:06:44.667] [KSPCF] Taking over stock loader. An exception will follow, this is intended.
[EXC 06:06:44.668] Exception: Terminating stock loader coroutine, this is intended and not an error
	KSPCommunityFixes.Performance.KSPCFFastLoader.GameDatabase_SetupMainLoaders_Prefix () (at <1ab895c297764334bc8ca0487ca3a837>:0)
	(wrapper dynamic-method) GameDatabase.GameDatabase.SetupMainLoaders_Patch1(GameDatabase)`

This error has cropped up since my very first test run of trying to get a modded game without any errors, pretty much running just with KSPCF installed. As you can see, this seems to be an entirely intentional, and explained, so I assume this is an oversight in terms of a parsing exception for error reporting. I'm not discounting that the error could be in the message saying it's not an error, though. 30000 line error log available on request.

### Operating system

Windows 10

### KSP version

1.12.5.3190

### Version of addon

V1.4.0

### Steps to reproduce the behavior or issue

1. Set up KSP with KSP Community Fixes and Exception Detector installed.
2. Load up (a steam version of?) KSP.
3. Be me, with my computer.
4. Get error every time, in regular, and ED logs, even with just these mods installed.

### Environment

```shell
?? Why is this a required field when the exact same information is asked for in other specific fields?? 

Kerbal Space Program - 1.12.5.3190 (WindowsPlayer x64)
ED V1.4.0
Only obviously relevant part of log included in comment, full log available if needed.
```

### How did you download and install this?

CurseForge (download and manual installation)

**Comment by Alpaccalypse** [comment] 2023-05-02 06:07
Sorry about aloof comment in secondary required field. Been up all night tweaking config files, so might not be thinking clearly; but I assume the understandably exhaustive information request, is in this case irrelevant. Unless this is not an expected error, contrary to what the log stated.

Great mod BTW, but liable to give me a nervous breakdown when using mods with KSP.

**Comment by zer0Kerbal** [comment] 2023-05-02 20:04
## Thank you for the bug report @Alpaccalypse 

Appreciate the frustration you express because in may ways I the same way concerning the KSP log(s). In fact tracking down and eliminating exc/err/wrn in the KSP.log is probably what started me on my KSP modding path.

For future reference drag+drop a zip/rar of the logs right into the report.

From what you are saying EXCD is working exactly as intended. It is KSPCF that is spamming your log with exceptions; which is exactly what EXCD was designed to report.

The legal council I am receiving is that as an author I shouldn't touch KSPCF since KSPCF _probably_ violates the EULA/ToS (as _probably_ Harmony does). This means providing anything more than the speculative support (next paragraph) is not allowed. 

### Tailor your EXCD experience: 

There is a simple and efficient way to stop things from appearing (other than removing kspcf) and that is to add a line to [GameData/godarklight/ExceptionDetector/Plugins/Settings.cfg)](https://github.com/zer0Kerbal/ExceptionDetector/blob/f8b198571b3d588e0b334d5f7b672b152fbf2473/GameData/godarklight/ExceptionDetector/Plugins/Settings.cfg)

something like:
`kspcf = KSPCF`

I believe that that line will 'filter' out all logging from that mod; and there are other ways to filter that are demonstrated in the settings.cfg

If you choose to add the line; kindly add a comment to this discussion so it can be included in the soon to be created FAKQ _(Frequently Asked Kerbal Questions_ page that shall be located here: [![image](https://user-images.githubusercontent.com/39887717/235758733-6b6f015b-4590-4307-9951-3675b8e43142.png)](https://zer0kerbal.github.io/ExceptionDetector)

### Including KSPCF in the _exception exception listing_

is not in the best interests of the players who have EXCD installed since it is KSPCF that is spamming the log with exceptions; it is an external issue and has to be fixed by KSPCF. 

### Issue template

It does need to be updated. カイゼン

Note to self: I really should add that fact to the issue template.

**Comment by zer0Kerbal** [comment] 2023-05-02 20:04
https://github.com/zer0Kerbal/ExceptionDetector/discussions/41

**Closed** 2023-05-02 20:10 UTC
Labels: issue: external, state: won't fix
